### ISSUE TITLE
Ask a question about UnuglifyJS repo

### ISSUE THREAD

**Issue by HaveF** [urialon/ECG#1]
Hi, urialon,
Because unuglifyjs has not issues tab, so I ask my question here, hope it is not too disturb.

I find your repo  [urialon/UnuglifyJS: A simpler open-source version of JavaScript deobfuscator JSNice](https://github.com/urialon/UnuglifyJS) do a lot based on the original repo.

Does it a working program? Does the install process changed(installed from source)? And Does it have some new features?

Thanks! :-)

**Comment by urialon** [comment]
Hi!
My UnuglifyJS repo is a modified version of "tech-srl/UnuglifyJS", which I
created for internal, research purposes.
Can I help somehow?

Uri

**Comment by HaveF** [comment]
Hi, Uri,

Thanks for your reply!
Because last commit of  [eth-srl/UnuglifyJS](https://github.com/eth-srl/UnuglifyJS) is submited 2 years ago. So I want to find something new. 
Do you add some new features to UnuglifyJS?

**Comment by urialon** [comment]
My version in mainly for internal usage, so it is not designed to be
friendly and useful.
You better use the original version.
Are you planning on using it to train models using Nice2Predict? Or do you
want to use it for de-minification?
If you plan only to use it to de-minify existing JavaScript code, you
should check out the following websites (these are all belong to the same
lab at ETH Zurich):
http://nice2predict.org/
http://www.jsnice.org/

If you plan to use it to train your own models using Nice2Predict, that's
where UnuglifyJS might be useful.

Uri

**Comment by HaveF** [comment]
Well, thanks for your type  and advice.

I put a file, about ~1.3M js, it throw lots of errors like this:

> Line 13094: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.

I do support the jsnice seems not work well in real use, but it is a really interesting idea.

Hope you have good luck in this research area :smile:

**Comment by urialon** [comment]
Thanks,
I'm familiar with these kinds of errors.
UnuglifyJS is based on UglifyJS which parses the JS file, and since then there were language updates which UnuglifyJS does not support. 
It is supposed to be possible to update UnuglifyJS to support the new features of the language, by updating the files that are taken from UglifyJS, but it may require some work. Good luck to you too.
